### ISSUE TITLE
Unable to find the codes

### ISSUE THREAD

**Issue by MirzaZain110** [mdtalalwasim/springboot-file-project-upload-file-directly-in-directory-folder#1]

**Comment by mdtalalwasim** [comment]
![Screenshot from 2024-11-12 16-09-57](https://github.com/user-attachments/assets/d11ad0d4-13d1-4c74-a70f-97c31e05d33d)
Thank you for your interest. Please navigate to this you will find all the code:

**Comment by MirzaZain110** [comment]
Hello @mdtalalwasim 
Actually, When I clone the repo, it shows up as empty
![Screenshot 2024-11-12 172418](https://github.com/user-attachments/assets/3842944a-2166-409d-add9-69851a0f1e48)
